/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Seguessi
 */
public class index extends javax.swing.JFrame {

    
    double valorOperacao, totalProposta;
    double alqPis;
    double valIcms, valPis, calcDifal, totalIRPJ, rjFCP;
    
    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        ImageIcon img = new ImageIcon("C:\\Users\\Seguessi\\Documents\\NetBeansProjects\\calculoImp\\src\\img/logo.png");
        this.setIconImage(img.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtValorOperacao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbContribuente = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        lblPorcDifal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAliqICMS = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblAlqICMS = new javax.swing.JFormattedTextField();
        lblPis = new javax.swing.JFormattedTextField();
        lblValDifal = new javax.swing.JFormattedTextField();
        lblTotIRPJ = new javax.swing.JFormattedTextField();
        lblTotCLSS = new javax.swing.JFormattedTextField();
        lblTotal = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        lblFCP = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        lblCargaTributaria = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PLANEJAMENTO TRIBUTÁRIO 2020 - ALPHENZ");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CÁLCULO IMPOSTO ETA / ETE - NCM: 8421.21.00");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Cálcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Fechar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("VALOR DA OPERAÇÃO:");

        txtValorOperacao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorOperacao.setToolTipText("Digite o valor da proposta sem \",\"");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("ESTADO DESTINO:");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "ES", "GO", "MT", "MS", "AL", "PI", "AC", "PA", "RR", "RO", "MG", "RJ", "PR", "SC", "RS", "DF", "BA", "CE", "MA", "PB", "PE", "RN", "SE", "AM", "AP", "TO" }));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText(" ICMS:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("PIS / COFINS:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("3.65%");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel8.setText("CONTRIBUINTE:");

        cbContribuente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NÃO" }));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("% DIFAL:");

        lblPorcDifal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPorcDifal.setText("%");
        lblPorcDifal.setToolTipText("");
        lblPorcDifal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("R$ DIFAL:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("IRPJ:");

        lblAliqICMS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAliqICMS.setText("%");
        lblAliqICMS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("CSLL:");

        jLabel11.setText("TOTAL DOS TRIBUTOS:");

        lblAlqICMS.setEditable(false);
        lblAlqICMS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        lblAlqICMS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblPis.setEditable(false);
        lblPis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        lblPis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblValDifal.setEditable(false);
        lblValDifal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        lblValDifal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lblValDifal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblValDifalActionPerformed(evt);
            }
        });

        lblTotIRPJ.setEditable(false);
        lblTotIRPJ.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lblTotIRPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTotIRPJActionPerformed(evt);
            }
        });

        lblTotCLSS.setEditable(false);
        lblTotCLSS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblTotal.setEditable(false);
        lblTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        lblTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lblTotal.setToolTipText("Total de impostos");

        jLabel13.setText("FCP:");

        lblFCP.setEditable(false);
        lblFCP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        lblFCP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lblFCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblFCPActionPerformed(evt);
            }
        });

        jLabel14.setText("CARGA TRIBUTÁRIA");

        lblCargaTributaria.setEditable(false);
        lblCargaTributaria.setForeground(new java.awt.Color(255, 0, 0));
        lblCargaTributaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        lblCargaTributaria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblCargaTributaria.setText("%");
        lblCargaTributaria.setToolTipText("Total de impostos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(3, 3, 3)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addGap(3, 3, 3)
                        .addComponent(lblCargaTributaria, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPorcDifal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValDifal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotIRPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotCLSS, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblAliqICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblAlqICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblPis))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtValorOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbContribuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFCP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbContribuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAliqICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlqICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPis, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPorcDifal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValDifal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel2)
                    .addComponent(lblTotIRPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotCLSS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblFCP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(lblCargaTributaria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Retorna o valor do ComboBox com a sigla do estado.    
        String estado = String.valueOf(cbEstado.getSelectedItem());
        
        String contribuente = String.valueOf(cbContribuente.getSelectedItem());
        
        //Retorna indice do ComboBox Estado
        int indiceUF = (cbEstado.getSelectedIndex());
        
        if(txtValorOperacao.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o valor da proposta", "Erro",JOptionPane.ERROR_MESSAGE);
        }
        valorOperacao = Double.parseDouble(txtValorOperacao.getText());
        
        //Cálculo de ICMS e PIS / COFINS por estado selecionado.
        if(estado == "SP"){
            valIcms = valorOperacao * 0.12;
            valPis = valorOperacao * (3.65 /100);
            lblAlqICMS.setText("R$" + String.valueOf(valIcms).format("%.2f", valIcms));
            lblPis.setText("R$" + String.valueOf(valPis).format("%.2f", valPis));
            lblPorcDifal.setText("0");
            lblValDifal.setText("0");
            lblAliqICMS.setText("12%");
        }
        else{
            valIcms = valorOperacao * 0.04;
            valPis = valorOperacao * (3.65 /100);
            lblAlqICMS.setText("R$" + String.valueOf(valIcms).format("%.2f", valIcms));
            lblPis.setText("R$" + String.valueOf(valPis).format("%.2f", valPis));
            lblAliqICMS.setText("4%");
        }
        
        if(contribuente == "SIM"){
            //Não paga Difal
            lblPorcDifal.setText("0");
            lblValDifal.setText("0");
        }
        else{
            //Paga Difal
            if(indiceUF == 1){
                lblPorcDifal.setText("8%");
                calcDifal = valorOperacao * 0.08;
                lblValDifal.setText("R$" + String.valueOf(calcDifal).format("%.2f", calcDifal));
            }
            else if(indiceUF >= 2 && indiceUF <=9){
                lblPorcDifal.setText("13%");
                calcDifal = valorOperacao * 0.13;
                lblValDifal.setText("R$" + String.valueOf(calcDifal).format("%.2f", calcDifal));
            }else if(indiceUF == 10){
                lblPorcDifal.setText("13.5%");
                calcDifal = valorOperacao * 0.135;
                lblValDifal.setText("R$" + String.valueOf(calcDifal).format("%.2f", calcDifal));
            }else if(indiceUF >= 11 && indiceUF <=26){
                lblPorcDifal.setText("14%");
                calcDifal = valorOperacao * 0.14;
                lblValDifal.setText("R$" + String.valueOf(calcDifal).format("%.2f", calcDifal));
            }else{
                lblPorcDifal.setText("0");
                lblValDifal.setText("0");
            }
        }
        
        double PresuncaoLucro = (valorOperacao * 0.08);
        double BaseCalcIRPJ = PresuncaoLucro * 0.15;
        if(PresuncaoLucro >= 20000){
            double AddIRPJ = (PresuncaoLucro - 20000) * 0.10;
            totalIRPJ = BaseCalcIRPJ + AddIRPJ;
            lblTotIRPJ.setText("R$" + String.valueOf(totalIRPJ).format("%.2f", totalIRPJ));
        }else{
            lblTotIRPJ.setText("--");
        }
        
        double PresuncaoLucroCSLL = (valorOperacao * 0.12) * 0.09;
        lblTotCLSS.setText("R$" + String.valueOf(PresuncaoLucroCSLL).format("%.2f", PresuncaoLucroCSLL));
              
        if(estado == "RJ"){
            rjFCP = valorOperacao * 0.02;
            lblFCP.setText(String.valueOf(rjFCP).format("%.2f", rjFCP));
        }else if(estado == "AL" || estado == "PI"){
            rjFCP = valorOperacao * 0.01;
            lblFCP.setText(String.valueOf(rjFCP).format("%.2f", rjFCP));
        }else{
            lblFCP.setText("Desconsiderar");
        }
        
        double total = valIcms + valPis + calcDifal + totalIRPJ + PresuncaoLucroCSLL + rjFCP;
        
        lblTotal.setText("R$" + String.valueOf(total).format("%.2f", total));
        double cargaTribuataria = (total / valorOperacao) * 100;
        lblCargaTributaria.setText(String.valueOf(cargaTribuataria).format("%.2f", cargaTribuataria) + "%");
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            txtValorOperacao.setText(""); 
            lblValDifal.setText("R$ 0,00");
             lblPorcDifal.setText("0,0%");
             lblPis.setText("R$ 0,00");
             lblAlqICMS.setText("R$ 0,00");
             lblPis.setText("R$ 0,00");
             lblAlqICMS.setText("0,0%");
             lblTotIRPJ.setText("R$ 0,00");
             lblTotCLSS.setText("R$ 0,00");
             lblCargaTributaria.setText("0");
             lblFCP.setText("R$ 0,00");
             lblTotal.setText("R$0,00");
             lblAliqICMS.setText("%");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblValDifalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblValDifalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblValDifalActionPerformed

    private void lblTotIRPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTotIRPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTotIRPJActionPerformed

    private void lblFCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblFCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFCPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbContribuente;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAliqICMS;
    private javax.swing.JFormattedTextField lblAlqICMS;
    private javax.swing.JFormattedTextField lblCargaTributaria;
    private javax.swing.JFormattedTextField lblFCP;
    private javax.swing.JFormattedTextField lblPis;
    private javax.swing.JLabel lblPorcDifal;
    private javax.swing.JFormattedTextField lblTotCLSS;
    private javax.swing.JFormattedTextField lblTotIRPJ;
    private javax.swing.JFormattedTextField lblTotal;
    private javax.swing.JFormattedTextField lblValDifal;
    private javax.swing.JTextField txtValorOperacao;
    // End of variables declaration//GEN-END:variables
}
